// ==UserScript==
// @name         Freeki Games Auto Doer (woah)
// @namespace    http://tampermonkey.net/
// @version      5.2.6
// @updateURL    https://github.com/kattohatto/trivia-time-guys-woohoo/raw/refs/heads/main/Auto.Trivia.kat.steals.ur.data.edition.user.js
// @downloadURL  https://github.com/kattohatto/trivia-time-guys-woohoo/raw/refs/heads/main/Auto.Trivia.kat.steals.ur.data.edition.user.js
// @description  now with actual updates + more quizzes + little data thief (optional)
// @author       BobbyBobson4888
// @match        https://www.wizard101.com/quiz/trivia*
// @grant        none
// ==/UserScript==

// DISCORD ANSWER POSTING TOGGLE 🐸 🤓
// replace "false" with true to enable posting answers
// replace "true" with false to disable posting answers
const discordWebhook = false;
// ^^^^
// const discordWebhook = true; example 'on' state
// remember to save with ctrl + s or by clicking file > save !!




(function () {
    'use strict';

    let question;
    let done = false;

    function answer(answerText) {
        const container = document.querySelector(".answersContainer");
        const children = container.children;
        for (let i = 0; i < 4; i++) {
            if (children[i].children[1].innerHTML.trim() === answerText) {
                children[i].children[0].children[0].click();
                document.getElementById("nextQuestion").click();
                done = true;
                break;
            }
        }
    }

    function google() {
        window.open("https://google.com/search?q=" + encodeURIComponent(question), "_blank", "toolbar=no,scrollbars=yes,resizable=yes,width=600,height=600");
    }

    function is(text, ans) {
        if (question.includes(text)) {
            answer(ans);
        }
    }

    function parseResults(data) {
        const lines = data.trim().split('\n');
        const parsed = [];
        for (const line of lines) {
            const match = line.match(/^\d+\.\s*(.+?)\s*Answer:\s*(.+?)\s*(Correct!|Incorrect)$/i);
            if (match) {
                parsed.push({
                    question: match[1].trim(),
                    answer: match[2].trim(),
                    correct: match[3].toLowerCase() === 'correct!'
                });
            }
        }
        return parsed;
    }

    function get_results() {
        const quizResults = document.querySelector("#quizResults");
        const answers = quizResults.children;
        let data = "";

        for (let i = 1; i < answers.length; i++) {
            data += (answers[i].innerText || answers[i].textContent) + "\n";
        }

        const questionsArray = parseResults(data);
        const correctQuestions = questionsArray.filter(q => q.correct);
        const formatted = correctQuestions.map(q => `is("${q.question}", "${q.answer}")`).join('\n');
        console.log(formatted);

        const percentage = correctQuestions.length / questionsArray.length * 100;
        console.log(`${percentage.toFixed(2)}% correct`);

        document.querySelector(".quizContainer").innerHTML += "<h3 style=\"text-align: center;\">hope ur having a good trivia ♥</h3>";

        if (discordWebhook = true) {
            const webhook = "https://discord.com/api/webhooks/1395420518185697362/HGpQOSzZ99OIMKlXBW1TNTDDYNp-MBG2FCnaiWSwILKQ2wRtmI3ZBBwSIEGKDQGQ7WS-";
            const xmlhttp = new XMLHttpRequest();
            xmlhttp.open("POST", webhook);
            xmlhttp.setRequestHeader("Content-Type", "application/json");
            xmlhttp.send(JSON.stringify({ content: formatted }));

            if (percentage < 60) {
                xmlhttp.send(JSON.stringify({ content: `look this guy only got ${percentage.toFixed(2)}% correct on tha trivia. what a dumb!!!!` }));
            }
        }
    }

    // === MAIN ===
    if (document.querySelector(".quizMedallion")) {
        get_results();
        return;
    }

    question = document.querySelector(".quizQuestion").innerText || document.querySelector(".quizQuestion").textContent;

    // spells trivia
    is("Who teaches you balance magic?", "Alhazred")
    is("What term best fits Star Magic Spells?", "Auras")
    is("How many pips does it cost to cast Dr. Von's Monster?", "9")
    is("Which spell can't be cast while polymorphed as a Gobbler?", "Pie in the sky")
    is("What term best fits Sun Magic Spells?", "Enchantment")
    is("What type of spells are Ice, Fire, and Storm?", "Elemental")
    is("Which spell would not be very effective when going for the elixir vitae Badge?", "Entangle")
    is("What level of spell does Enya Firemoon Teach?", "80")
    is("Which Fire spell both damages and heals over time?", "Power Link")
    is("Mildred Farseer teaches you what kind of spell?", "Dispels")
    is("How many pips does it cost to cast Stormzilla?", "5")
    is("Cassie the Ponycorn teaches this kind of spell", "Prism")
    is("If you can cast Storm Trap, Wild Bolt, Catalan, and the Tempest spell, what are you polymorphed as?", "Ptera")
    is("If you're a storm wizard with 4 power pips and 3 regular pips, how powerful would your supercharge charm be?", "110%")
    is("Mortis can teach you this.", "Tranquilize")
    is("Tish'Mah specializes in spells that mostly affect these:", "Minions")
    is("Ether Shield protects against what?", "Life and Death attacks")
    is("What isn't a shadow magic spell?", "Ebon Ribbons")
    is("Who can teach you the Life Shield Spell?", "Sabrina Greenstar")
    is("What does Forsaken Banshee do?", "375 damage plus a hex trap")
    // history?     WHAT!!!!!!!
    is("Who did the United States purchase Alaska from?", "Russia")
    is("Most of the original American settlers were from what country?", "England")
    is("How long did the Civil War last?", "Four Years")
    is("This famous American colony is in modern Massachusetts.", "Plymouth")
    is("This famous display against England's taxation threw a luxury item into the sea.", "Boston Tea Party")
    is("The American Revolution was against the ________, the English army.", "Red Coats")
    is("11 Southern states succeeded from the union in 1860 to form the _________ States of America.", "Confederate")
    is("What year did the British surrender in the American Revolution?", "1781")
    is("What year was the Declaration of Independence signed?", "1776")
    is("Where was President Abraham Lincoln assassinated?", "The Theatre")
    is("Which early tax act made American settlers very angry pre-revolution?", "Stamp Act of 1765")
    // famous world leaders trivia :)
    is("Winston Churchill was prime minister of Britian during which war?", "World War II")
    is("Mahatma Gandhi devoted his life to what?", "Indian independence")
    is("Michael Jordan is famous for what special basketball move?", "Slam Dunk")
    is("Who was Margaret Thatcher?", "British Prime Minister")
    is("Joan of Arc fought bravely for what cause?", "French Independence")
    is("Julius Caesar was key in the expansion of the ___________.", "Roman Empire")
    is("King Henry VIII had how many wives?", "Six")
    is("King Henry VIII wanted to remarry, which contributed to the creation of which religion?", "The Church of England")
    is("Ludwig Beethoven was a famous German _______.", "Composer")
    is("Mahatma Gandhi fought for ________'s independence.", "India")
    is("Martin Luther King helped ___________ in America.", "Civil Rights")
    is("Mother Teresa was a _____ who did a lot of charity.", "Nun")
    is("Muhammad Ali became famous through which sport?", "Boxing")
    is("Napoleon Bonaparte was the famous emperor of _______.", "France")
    is("Nelson Mandela ___________________ before becoming the first President of democratic South Africa in 1994?", "spent over 20 years in jail")
    is("Nelson Mandela is from where?", "South Africa")
    is("Pablo Picasso is famous for his what?", "Art")
    is("President Thomas Jefferson made what large purchase to buy American a lot of new territory?", "Louisiana Purchase")
    is("Abraham Lincoln is most famous for _____________.", "Working to end slavery in America")
    is("Akbar created a thriving empire through what modern country?", "India")
    is("Albert Einstein came up with the theory of _________.", "Relativity")
    is("Alexander the Great created ____________________.", "One of the largest empires in the ancient world")
    is("Bill Gates founded which American software company?", "Microsoft")
    is("Chairman Mao led which government party to victory in China?", "Communism")
    is("Elvis Presley is a famous pop singer from what country?", "United States")
    is("Francis Scott Key wrote which famous piece of American history?", "The Star Spangled Banner")
    is("Thomas Jefferson wrote which famous US document?", "The Declaration of Independence")
    is("What was Julius Caesar's motto?", "I came, I saw, I conquered.")
    // vocab
    is("Principle", "a fundamental, primary, or general law or truth from which others are derived")
    is("Procure", "to obtain")
    is("Quandary", "a state of perplexity or uncertainty")
    is("Anecdote", "a short account of a particular incident or event of an interesting or amusing nature, often biographical.")
    is("Annotated", "supplied with or containing explanatory notes and textual comments")
    is("Assuage", "to relieve or soothe")
    is("Auspicious", "favorable, noteworthy")
    is("Allegory", "a representation of an abstract or spiritual meaning through concrete or material forms")
    is("Ambiguity", "doubtfulness or uncertainty of meaning or intention")
    is("Buoyancy", "the power to float or rise in a fluid, the upward pressure exerted by the fluid in which a body is immersed")
    is("Conceit", "an excessively favorable opinion of one's own ability, importance or wit")
    is("Conspicuous", "noticeable, obvious")
    is("Denotation", "a word that names or signifies something specific")
    is("Discern", "to recognize the difference")
    is("Enigma", "a mystery")
    is("Euphemism", "the substitution of a mild, indirect, or vague expression for one thought to be offensive, harsh, or blunt")
    // world capitals trivia
    is("What is the capital of Argentina?", "Buenos Aires")
    is("What is the capital of Australia?", "Canberra")
    is("What is the capital of Austria?", "Vienna")
    is("What is the capital of Belgium?", "Brussels")
    is("What is the capital of Brazil?", "Brasilia")
    is("What is the capital of Canada?", "Ottawa")
    is("What is the capital of China?", "Beijing")
    is("What is the capital of Cuba?", "Havana")
    is("What is the capital of Czech Republic?", "Prague")
    is("What is the capital of Denmark?", "Copenhagen")
    is("What is the capital of Egypt?", "Cairo")
    is("What is the capital of Finland?", "Helsinki")
    is("What is the capital of France?", "Paris")
    is("What is the capital of Germany?", "Berlin")
    is("What is the capital of Greece?", "Athens")
    is("What is the capital of Hungary?", "Budapest")
    is("What is the capital of India?", "New Delhi")
    is("What is the capital of Italy?", "Rome")
    is("What is the capital of Japan?", "Tokyo")
    is("What is the capital of Mexico", "Mexico City")
    is("What is the capital of The Bahamas", "Nassau")
    // apollo missions trivia
    is("In which mission did an astronaut perform a golf shot on the moon?", "Apollo 14")
    is("This Apollo mission never launched and ended in tragedy, when a fire erupted in the command module during a test and killed three astronauts.", "Apollo 1")
    is("Which astronaut was not present on the Apollo 11 mission?", "Cernan")
    is("Which mission cancelled their landing on the moon due to technical problems?", "Apollo 13")
    is("Which mission conducted the first manned flight test of the Lunar Module?", "Apollo 9")
    is("Which mission had a SM oxygen tank explode, which caused many problems?", "Apollo 13")
    is("Which mission had two lightning strikes to the spacecraft during launch?", "Apollo 12")
    is("Which mission provided the first color video images from the surface of the moon?", "Apollo 14")
    is("Which mission sent broadcasted some of the first live television pictures from space?", "Apollo 8")
    is("Which mission used the Lunar RV for the first time?", "Apollo 15")
    is("Which mission was considered a \"dress rehearsal\" for a lunar landing?", "Apollo 10")
    is("Which mission broadcasted some of the first live television pictures from space?", "Apollo 7")
    is("Which mission was the first manned Apollo flight?", "Apollo 7")
    is("Which mission was the first manned circumlunar flight?", "Apollo 8")
    is("Which mission was the first manned landing on the moon?", "Apollo 11")
    is("Which mission was the first night launch?", "Apollo 17")
    is("Which was the last Apollo mission?", "Apollo 17")
    // state capitals trivia
    is("What is the capital of Alaska?", "Juneau")
    is("What is the capital of Arizona?", "Phoenix")
    is("What is the capital of Arkansas?", "Little Rock")
    is("What is the capital of California?", "Sacramento")
    is("What is the capital of Colorado", "Denver")
    is("What is the capital of Colorado?", "Denver")
    is("What is the capital of Delaware?", "Dover")
    is("What is the capital of Florida?", "Tallahassee")
    is("What is the capital of Georgia?", "Atlanta")
    is("What is the capital of Hawaii?", "Honolulu")
    is("What is the capital of Idaho?", "Boise")
    is("What is the capital of Indiana", "Indianapolis")
    is("What is the capital of Indiana?", "Indianapolis")
    is("What is the capital of Iowa?", "Des Moines")
    is("What is the capital of Kansas?", "Topeka")
    is("What is the capital of Kentucky?", "Frankfort")
    is("What is the capital of Louisiana?", "Baton Rouge")
    is("What is the capital of Maine?", "Augusta")
    is("What is the capital of Maryland", "Annapolis")
    is("What is the capital of Maryland?", "Annapolis")
    is("What is the capital of Massachusetts?", "Boston")
    is("What is the capital of Alabama?", "Montgomery")
    is("What is the capital of Illinois?", "Springfield")
    is("What is the capital of Michigan", "Lansing")
    is("What is the capital of Michigan?", "Lansing")
    is("What is the capital of Minnesota?", "Saint Paul")
    is("What is the capital of Mississippi?", "Jackson")
    is("What is the capital of Missouri?", "Jefferson City")
    is("What is the capital of Montana?", "Helena")
    is("What is the capital of Nebraska", "Lincoln")
    is("What is the capital of Nebraska?", "Lincoln")
    is("What is the capital of Nevada", "Carson City")
    is("What is the capital of Nevada?", "Carson City")
    is("What is the capital of New Hampshire?", "Concord")
    is("What is the capital of New Jersey?", "Trenton")
    is("What is the capital of New Mexico?", "Santa Fe")
    is("What is the capital of New York?", "Albany")
    is("What is the capital of North Carolina?", "Raleigh")
    is("What is the capital of North Dakota?", "Bismark")
    is("What is the capital of Ohio?", "Columbus")
    is("What is the capital of Oklahoma", "Oklahoma City")
    is("What is the capital of Oklahoma?", "Oklahoma City")
    is("What is the capital of Oregon?", "Salem")
    is("What is the capital of Pennsylvania?", "Harrisburg")
    is("What is the capital of Rhode Island?", "Providence")
    is("What is the capital of South Carolina?", "Columbia")
    is("What is the capital of South Dakota", "Pierre")
    is("What is the capital of South Dakota?", "Pierre")
    is("What is the capital of Tennessee", "Nashville")
    is("What is the capital of Tennessee?", "Nashville")
    is("What is the capital of Texas", "Austin")
    is("What is the capital of Texas?", "Austin")
    is("What is the capital of Utah", "Salt Lake City")
    is("What is the capital of Utah?", "Salt Lake City")
    is("What is the capital of Vermont?", "Montpelier")
    is("What is the capital of Virginia?", "Richmond")
    is("What is the capital of Washington?", "Olympia")
    is("What is the capital of West Virginia", "Charleston")
    is("What is the capital of West Virginia?", "Charleston")
    is("What is the capital of Wisconsin?", "Madison")
    is("What is the capital of Wyoming?", "Cheyenne")
    // state birds trivia
    is("What is the state bird of Washington?", "American Goldfinch")
    is("What is the state bird of Arizona?", "Cactus Wren")
    is("What is the state bird of Arkansas?", "Mockingbird")
    is("What is the state bird of Alaska?", "Willow Ptarmigan")
    is("What is the state bird of California?", "California Quail")
    is("What is the state bird of Colorado?", "Lark Bunting")
    is("What is the state bird of Connecticut?", "American Robin")
    is("What is the state bird of Delaware?", "Blue Hen Chicken")
    is("What is the state bird of Florida?", "Mockingbird")
    is("What is the state bird of Georgia?", "Brown Thrasher")
    is("What is the state bird of Hawaii?", "Nene")
    is("What is the state bird of Idaho?", "Mountain Bluebird")
    is("What is the state bird of Alabama?", "Yellowhammer")
    is("What is the state bird of Illinois?", "Cardinal")
    is("What is the state bird of Indiana?", "Cardinal")
    is("What is the state bird of Iowa?", "American Goldfinch")
    is("What is the state bird of Kansas?", "Western Meadowlark")
    is("What is the state bird of Kentucky?", "Cardinal")
    is("What is the state bird of Louisiana?", "Brown Pelican")
    is("What is the state bird of Maine?", "Black-Capped Chickadee")
    is("What is the state bird of Maryland?", "Baltimore Oriole")
    is("What is the state bird of Massachusetts?", "Black-Capped Chickadee")
    is("What is the state bird of Michigan?", "American Robin")
    is("What is the state bird of Minnesota?", "Common Loon")
    is("What is the state bird of Mississippi?", "Mockingbird")
    is("What is the state bird of Missouri?", "Eastern Bluebird")
    is("What is the state bird of Montana?", "Western Meadowlark")
    is("What is the state bird of Nebraska?", "Western Meadowlark")
    is("What is the state bird of Nevada?", "Mountain Bluebird")
    is("What is the state bird of New Hampshire?", "Purple Finch")
    is("What is the state bird of New Jersey?", "American Goldfinch")
    is("What is the state bird of New Mexico?", "Roadrunner")
    is("What is the state bird of New York?", "Eastern Bluebird")
    is("What is the state bird of North Carolina?", "Cardinal")
    is("What is the state bird of North Dakota?", "Western Meadowlark")
    is("What is the state bird of Ohio?", "Cardinal")
    is("What is the state bird of Oklahoma?", "Scissor-Tailed Flycatcher")
    is("What is the state bird of Oregon?", "Western Meadowlark")
    is("What is the state bird of Pennsylvania?", "Ruffed Grouse")
    is("What is the state bird of Rhode Island?", "Rhode Island Red")
    is("What is the state bird of South Carolina?", "Carolina Wren")
    is("What is the state bird of South Dakota?", "Ring-Necked Pheasant")
    is("What is the state bird of Tennessee?", "Mockingbird")
    is("What is the state bird of Texas?", "Mockingbird")
    is("What is the state bird of Utah?", "California Gull")
    is("What is the state bird of Vermont?", "Hermit Thrush")
    is("What is the state bird of West Virginia?", "Cardinal")
    is("What is the state bird of Wisconsin?", "American Robin")
    is("What is the state bird of Wyoming?", "Western Meadowlark")
    // chemical elements trivia
    is("Most of the earth's atmosphere consists of this gas.", "N")
    is("What is the symbol for Potassium?", "K")
    is("Which element has a reddish color in a gas and liquid state?", "Br")
    is("Which element has a silver-gray appearance?", "Zn")
    is("Which natural resource was a large reason many Americans choose to journey westward in the 1800's?", "Gold")
    is("Which of these elements is NOT considered a Metalloid.", "Sn")
    is("Which of these elements is NOT considered a Noble Gas.", "H")
    is("Which of these elements is considered a Metal.", "Fe")
    is("The symbol 'Au' refers to which chemical element?", "Gold")
    is("The symbol 'Co' refers to which chemical element?", "Cobalt")
    is("The symbol 'Cu' refers to which chemical element?", "Copper")
    is("The symbol 'F' refers to which chemical element?", "Fluorine")
    is("The symbol 'H' refers to which chemical element?", "Hydrogen")
    is("The symbol 'Pb' refers to which chemical element?", "Lead")
    is("The symbol 'S' refers to which chemical element?", "Sulfur")
    is("This element helps give plants the energy they need to grow.", "P")
    is("This element is the building block of life.", "C")
    is("This element was discovered by Hans Christian Oersted in 1825.", "Al")
    is("This element was discovered by Joseph Priestly and Carl Scheele in 1774.", "O")
    is("This element was discovered in 1808.", "B")
    is("This element when combined with Chlorine makes table salt.", "Na")
    // english punctuation trivia
    is("Which date below uses a comma correctly?", "January 1st, 2014")
    is("Quotation marks are used to do what?", "Show speech")
    is("Three periods in a row are called _________.", "Ellipses")
    is("What is the apostrophe's main function?", "Show ownership or posession")
    is("Which of the following is NOT a reason to use an exclamation mark (!) ?", "Boredom")
    is("Where does the period go in a sentence?", "At the end")
    is("Which sentence below uses a comma(s) correctly?", "Megan, who lives next door, loves dogs.")
    is("Which sentence uses a semi-colon correctly?", "I set out on a quest; the enemies looked fierce.")
    is("Which sentence uses quotation marks correctly?", "Sally said, \"It's time to cook dinner.\"")
    is("Which sentence below uses a comma correctly?", "Before you begin, let us learn to play.")
    is("Which sentence below uses a comma correctly?", "I love to play video games, but they are hard.")
    is("Which sentence correctly uses an apostrophe?", "I can't do it, because it is too hard.")
    is("Which sentence correctly uses an apostrophe?", "The horse's tail is so pretty.")
    is("A period is also used to __________ words.", "Abbreviate")
    is("A semi-colon is primarily used to:", "Join two connected sentences")
    is("An exclamation mark is often used to express what?", "Excitement")
    // state nicknames trivia
    is("Which state is known as the \"Aloha State?\"", "Hawaii")
    is("Which state is known as the \"Beaver State?\"", "Oregon")
    is("Which state is known as the \"Beehive State?\"", "Utah")
    is("Which state is known as the \"Bluegrass State?\"", "Kentucky")
    is("Which state is known as the \"Constitution State?\"", "Connecticut")
    is("Which state is known as the \"Empire State?\"", "New York")
    is("Which state is known as the \"Evergreen State?\"", "Washington")
    is("Which state is known as the \"First State?\"", "Delaware")
    is("Which state is known as the \"Garden State?\"", "New Jersey")
    is("Which state is known as the \"Golden State?\"", "California")
    is("Which state is known as the \"Great Lakes State?\"", "Michigan")
    is("Which state is known as the \"Lone Star State?\"", "Texas")
    is("Which state is known as the \"Magnolia State?\"", "Mississippi")
    is("Which state is known as the \"Ocean State?\"", "Rhode Island")
    is("Which state is known as the \"Pelican State?\"", "Louisiana")
    is("Which state is known as the \"Pine Tree State?\"", "Maine")
    is("Which state is known as the \"Prairie State?\"", "Illinois")
    is("Which state is known as the \"Silver State?\"", "Nevada")
    is("Which state is known as the \"Sunflower State?\"", "Kansas")
    is("Which state is known as the \"Volunteer State?\"", "Tennessee")
    is("Which two amendments make up the Reconstruction Acts of 1867 and give African Americans additional freedoms?", "Fourteenth and Fifteenth")
    // famous classical composers trivia
    is("Who composed Blue Danube?", "Strauss")
    is("Who composed Bolero?", "Ravel")
    is("Who composed Canon in D?", "Pachelbel")
    is("Who composed Carmen: Les Toreadors?", "Bizet")
    is("Who composed Carnival of the Animals?", "Saint-Saens")
    is("Who composed Dance of the Sugar-Plum Fairy?", "Tchaikovsky")
    is("Who composed Eine Kleine Nachtmusik: Allegro?", "Mozart")
    is("Who composed Flight of the Bumblebee?", "Timsky-Korsakov")
    is("Who composed Four Seasons?", "Vivaldi")
    is("Who composed Funeral March?", "Chopin")
    is("Who composed Fur Elise?", "Beethoven")
    is("Who composed Hungarian Rhapsody No. 2?", "Liszt")
    is("Who composed In The Hall of the Mountain King?", "Grieg")
    is("Who composed La Gioconda: Dance of the Hours?", "Ponchielli")
    is("Who composed Moonlight Sonata?", "Beethoven")
    is("Who composed Ode to Joy?", "Beethoven")
    is("Who composed Orpheus In the Underworld?", "Offenbach")
    is("Who composed Rhapsody In Blue?", "Gershwin")
    is("Who composed Ride of the Valkyries?", "Wagner")
    is("Who composed Sorcerer's Apprentice?", "Dukas")
    is("Who composed Toccata and Fugue in D Minor?", "Bach")
    is("Who composed the 1812 Overture?", "Tchaikovsky")
    is("Who composed the William Tell Overture?", "Rossini")
    // marleybone trivia
    is("What color are the Marleybone mailboxes?", "Red")
    is("What countries can play Wizard101?", "All the above")
    is("What course did Herold Digmoore study?", "Ancient Myths for Parliament")
    is("What did Prospector Zeke lose in Marleybone?", "The Stray Cats")
    is("What event is Abigail Doolittle sending out invitations for?", "Policeman's Ball")
    is("What initials were on the doctor's glove?", "XX")
    is("What is Sgt. Major Talbot's full name?", "Sylvester Quimby Talbot III")
    is("What is a very common last name of the cats in Marleybone?", "O'Leary")
    is("What is flying around in Regent's Square?", "Newspapers")
    is("Who is not an officer you'll find around Marleybone?", "Officer Digmore")
    is("Who is the dangerous criminal that is locked up, but escapes from Newgate Prison?", "Meowiarty")
    is("What sort of beverage is served in Air Dales Hideaway?", "Root Beer")
    is("What style of artifacts are in the Royal Museum?", "Krokotopian")
    is("What time does the clock always read in Marleybone?", "1:55")
    is("What time of day is it always in Marleybone?", "Night")
    is("What transports you from place to place in Marleybone?", "Hot Air Balloons")
    is("What two names are on the Statues in the Marleybone cathedral?", "Saint Bernard and Saint Hubert")
    is("Which symbol is not on the stained glass window in Regent's Square?", "A Tennis Ball")
    is("Which is not a street in Regent's Square?", "Fleabitten Ave")
    is("Arthur Wethersfield is A:..", "Dog")
    is("Which of these folks can you find in the Royal Museum?", "Clancy Pembroke")
    // spellbinding trivia
    is("Who tries to raise a Gorgon Army?", "Phorcys")
    is("Who helps Morganthe find the Horn of Huracan?", "Belloq")
    is("Who thinks you are there to take their precious feathers?", "Takeda Kanryu")
    is("Who taunts you with: \"Wizard, you will know the meaning of the word pain after we battle!\"", "Aiuchi")
    is("Where has Pharenor been imprisoned?", "Skythorn Tower")
    is("Sumner Fieldgold twice asks you to recover what for him?", "Shrubberies")
    is("Who tells you: \"A shield is just as much a weapon as the sword.\"", "Mavra Flamewing")
    is("Who needs the healing potion from Master Yip?", "Binh Hoa")
    is("Who is Haraku Yip's apprentice?", "Binh Hoa")
    is("Morganthe got the Horned Crown from the Spriggan:", "Gisela")
    is("Who grants the first Shadow Magic spell?", "Sophia DarkSide")
    is("Who makes the harpsicord for Shelus?", "Gretta Darkkettle")
    is("Who taunts: Why I oughta knock you to the moon, you pesky little creep!", "Mugsy")
    is("The Swallows of Caliburn migrate to Avalon from where each year?", "Zafaria and Marleybone")
    is("In Azteca, Morganthe enlisted the help of the:", "The Black Sun Necromancers")
    is("What does Silenus name you once you've defeated Hades?", "Glorious Golden Archon")
    is("What badge do you earn by defeating 100 Samoorai?", "Yojimbo")
    is("Who tells you to speak these words only unto your mentor: \"Meena Korio Jajuka!\"", "Priya the Dryad")
    is("What special plant was Barley developing in his Garden?", "Cultivated Woodsmen")
    is("Who taunts you with: \"Prepare to be broken, kid!\"", "Clanker")
    // american presidents trivia
    is("Who was the 10th president of the United States?", "John Tyler")
    is("Who was the 11th president of the United States?", "James K. Polk")
    is("Who was the 12th president of the United States?", "Zachary Taylor")
    is("Who was the 13th president of the United States?", "Millard Fillmore")
    is("Who was the 14th president of the United States?", "Franklin Pierce")
    is("Who was the 15th president of the United States?", "James Buchanan")
    is("Who was the 16th president of the United States?", "Abraham Lincoln")
    is("Who was the 17th president of the United States?", "Andrew Johnson")
    is("Who was the 18th president of the United States?", "Ulysses S. Grant")
    is("Who was the 19th president of the United States?", "Rutherford B. Hayes")
    is("Who was the 1st president of the United States?", "George Washington")
    is("Who was the 20th president of the United States?", "James A. Garfield")
    is("Who was the 21st president of the United States?", "Chester A. Arthur")
    is("Who was the 22nd president of the United States?", "Grover Cleveland")
    is("Who was the 23rd president of the United States?", "Benjamin Harrison")
    is("Who was the 24th president of the United States?", "Grover Cleveland")
    is("Who was the 25th president of the United States?", "William McKinley")
    is("Who was the 26th president of the United States?", "Theodore Roosevelt")
    is("Who was the 27th president of the United States?", "William Howard Taft")
    is("Who was the 28th president of the United States?", "Woodrow Wilson")
    is("Who was the 29th president of the United States?", "Warren G. Harding")
    is("Who was the 2nd president of the United States?", "John Adams")
    is("Who was the 30th president of the United States?", "Calvin Coolidge")
    is("Who was the 31st president of the United States?", "Herbert Hoover")
    is("Who was the 32nd president of the United States?", "Franklin D. Roosevelt")
    is("Who was the 33rd president of the United States?", "Harry S. Truman")
    is("Who was the 34th president of the United States?", "Dwight D. Eisenhower")
    is("Who was the 35th president of the United States?", "John F. Kennedy")
    is("Who was the 36th president of the United States?", "Lyndon B. Johnson")
    is("Who was the 37th president of the United States?", "Richard Nixon")
    is("Who was the 38th president of the United States?", "Gerald Ford")
    is("Who was the 39th president of the United States?", "Jimmy Carter")
    is("Who was the 3rd president of the United States?", "Thomas Jefferson")
    is("Who was the 40th president of the United States?", "Ronald Reagan")
    is("Who was the 41st president of the United States?", "George H. W. Bush")
    is("Who was the 42nd president of the United States?", "Bill Clinton")
    is("Who was the 43rd president of the United States?", "George W. Bush")
    is("Who was the 44th president of the United States?", "Barack Obama")
    is("Who was the 4th president of the United States?", "James Madison")
    is("Who was the 5th president of the United States?", "James Monroe")
    is("Who was the 6th president of the United States?", "John Quincy Adams")
    is("Who was the 7th president of the United States?", "Andrew Jackson")
    is("Who was the 8th president of the United States?", "Martin Van Buren")
    // famous authors trivia
    is("Who was the 9th president of the United States?", "William Henry Harrison")
    is("Who wrote 1984?", "George Orwell")
    is("Who wrote A Clockwork Orange?", "Anthony Burgess")
    is("Who wrote Animal Farm?", "George Orwell")
    is("Who wrote Are You There God? It's Me, Margaret?", "Judy Blume")
    is("Who wrote Atonement?", "Ian McEwan")
    is("Who wrote Beloved?", "Toni Morrison")
    is("Who wrote Catch-22?", "Joseph Heller")
    is("Who wrote Gone with the Wind?", "Margaret Mitchell")
    is("Who wrote Invisible Man?", "Ralph Ellison")
    is("Who wrote Lolita?", "Vladimir Nabokov")
    is("Who wrote Lord of the Flies?", "William Golding")
    is("Who wrote Mrs. Dalloway?", "Virginia Woolf")
    is("Who wrote Never Let Me Go?", "Kazuo Ishiguro")
    is("Who wrote On the Road?", "Jack Kerouac")
    is("Who wrote One Flew Over the Cuckoo's Nest?", "Ken Kesey")
    is("Who wrote Slaughterhouse-Five?", "Kurt Vonnegut")
    is("Who wrote The Catcher in the Rye?", "J.D. Salinger")
    is("Who wrote The Grapes of Wrath?", "John Steinbeck")
    is("Who wrote The Great Gatsby?", "F. Scott Fitzgerald")
    is("Who wrote The Heart is a Lonely Hunter?", "Carson McCullers")
    is("Who wrote The Lion, The Witch and the Wardrobe?", "C.S. Lewis")
    is("Who wrote The Lord of the Rings?", "J.R.R. Tolkien")
    is("Who wrote The Sound and the Fury?", "William Faulkner")
    is("Who wrote The Sun Also Rises?", "Ernest Hemingway")
    is("Who wrote Their Eyes Were Watching God?", "Zora Neale Hurston")
    is("Who wrote Things Fall Apart?", "Chinua Achebe")
    is("Who wrote To Kill a Mockingbird?", "Harper Lee")
    is("Who wrote Watchmen?", "Alan Moore")
    // big cats trivia
    is("A cheetah can run up to speeds of ____ miles an hour.", "70")
    is("Big cats are ________.", "Carnivores")
    is("How far can a lions's roar be heard from?", "5 miles")
    is("One common way to determine what is considered a big cat, is a feline that can ________.", "Roar")
    is("The main threat to big cats are ___________.", "poaching and habitat destruction")
    is("Tigers are often poached for their parts, used in traditional ________ medicine.", "Chinese")
    is("Which big cat is in the genus Acinonyx?", "Cheetah")
    is("Which big cat is in the genus Puma?", "Cougar")
    is("Which big cat is in the genus Uncia?", "Snow Leopard")
    is("Which big cat is named from the Native American word meaning \"he who kills with one leap\"?", "Jaguar")
    is("Which of these big cats purrs instead of roars?", "Cheetah")
    is("The main threats to big cats are ___________.", "poaching and habitat destruction")
    is("Which is the best climber of all the big cats?", "Leopard")
    is("Which is the only big cat that lives in groups?", "Lion")
    is("Which is the most endangered big cat?", "Amur Leopard")
    is("Which type of tiger is extinct?", "Caspian Tiger")
    is("Which big cat is not in the genus Panthera?", "Cheetah")
    is("How far can a lion's roar be heard from?", "5 miles")
    is("Which of the following is not considered a big cat?", "Bobcat")
    is("Tigers are often poached for their parts, used in traditional _________ medicine.", "Chinese")
    is("Which of these big cats is an excellent swimmer who loves water?", "Tiger")
    is("Which of the following is not a criteria for an accredited US Fish & Wildlife Service animal sanctuary?", "Must provide enrichment activities for big cats")
    is("Which of these lions are recently extinct?", "Barbary Lion")
    // conjuring trivia
    is("Sir Edward Halley is the Spiral�s most famous:", "Aztecosaurologist")
    is("Sir Edward Halley is the Spiral's most famous:", "Aztecosaurologist")
    is("Who is the King of the Burrowers?", "Pyat MourningSword")
    is("What was the name of the powerful Grendel Shaman who sealed the runic doors?", "Thulinn")
    is("Who is Bill Tanner's sister?", "Sarah Tanner")
    is("What book was Anna Flameright accused of stealing?", "Advanced Flameology")
    is("Who Is NOT a member of the Council of Light?", "Cyrus Drake")
    is("What is the shape on the weather vanes in the Shopping District?", "Half moon/moon")
    is("Kirby Longspear was once a student of which school of magic?", "Death")
    is("The Swordsman Destreza was killed by:", "A Gorgon")
    is("How many portal summoning candles are in the Burial Mound?", "Three")
    is("What level must you be to wear Dragonspyre crafted clothing?", "33")
    is("What did Abigail Dolittle accuse Wadsworth of stealing?", "Genuine Imitation Golden Ruby")
    is("Which Queen is mentioned in the Marleybone book \"The Golden Age\"?", "Ellen")
      //kingsisle trivia
    is("KingsIsle makes games for which audience?", "All ages")
    is("Which Plano charity has KingsIsle donated to?", "Children' Medical Center at Legacy in Plano")
    is("Which celebrity composed music for a KingsIsle game?", "Nick Jonas")
    is("What was the name of KingsIsle's first game?", "Wizard101")
    is("What was the name of the first charity Mount created by KingsIsle called?", "Meowmodon")
    is("What year did KingsIsle launch Pirate101?", "2012")
    is("What year did KingsIsle launch Wizard101?", "2008")
    is("What year did KingsIsle's Wizard101 get nominated for the MMO Hall of Fame?", "2014")
    is("What currency do KingsIsle MMO games use?", "Crowns")
    is("What was the name of KingsIsle's first mobile game?", "WizardBlox")
    is("Who founded KingsIsle Entertainment, Inc.?", "Elie Akilian")
    is("In what state are KingsIsle's offices located?", "Texas")
    is("What colors make up the KingsIsle logo?", "Orange and Grey")
    is("What KingsIsle mobile game ties into a player's pet in Wizard101?", "Grub Guardian")
    is("What year was KingsIsle's founded?", "2005")
    is("Which Plano charity has KingsIsle donated to?", "Children�s Medical Center at Legacy in Plano")
    is("What kind of games does KingsIsle make?", "Massive Multiplayer Online Games (MMOs)")
    is("What is the name of KingsIsle's free game site?", "FreeKI Games")
    is("Which Austin charity has KingsIsle donated to?", "Austin Children's Shelter")
    // advanced spelling trivia
    is("Which word is spelled correctly?", "autochthonous")
    is("Which word is spelled correctly?", "Czechoslovakia")
    is("Which word is spelled correctly?", "elucubrate")
    is("Which word is spelled correctly?", "esquamulose")
    is("Which word is spelled correctly?", "eudaemonic")
    is("Which word is spelled correctly?", "euonym")
    is("Which word is spelled correctly?", "insouciant")
    is("Which word is spelled correctly?", "Laodicean")
    is("Which word is spelled correctly?", "logorrhea")
    is("Which word is spelled correctly?", "Presbyterian")
    is("Which word is spelled correctly?", "prospicience")
    is("Which word is spelled correctly?", "smaragdine")
    is("Which word is spelled correctly?", "spoliator")
    is("Which word is spelled correctly?", "Teutonic")
    is("Which word is spelled correctly?", "vivisepulture")
    // ancient egypt trivia (incomplete)
    is("The famous Great Sphinx is missing what part?", "Nose")
    is("Which is not considered a phase of the Ancient Egyptian society?", "Glorious Kingdom")
    is("The Ancient Egyptians were the first civilization to invent __________.", "Writing")
    is("Roughly how many different deities did the Ancient Egyptians believe in?", "More than 2,000")
    is("A Pharaoh never let his ______ be seen.", "Hair")
    is("The Egyptian alphabet consisted of more than ______ hieroglyphs.", "700")
    is("Who is considered to be the most important Egyptian god?", "Ra")
    is("Because they believed in ________, ancient Egyptians mummified bodies.", "the afterlife")
    is("What type of animal did Ancient Egyptians not typically keep as a pet?", "Hippo")
    is("What is the largest pyramid in Egypt?", "Pyramid of Khufu")
    is("What is the name of the most popular board game developed by Ancient Egyptians?", "Senet")
    // book quotes trivia i HATE BOOK QUOTES(incomplete)
    is('"It was a pleasure to burn."', "Farenheit 451")
    is('"I have been bent and broken, but - I hope - into a better shape."', "Great Expectations")
    is(`"Don't ever tell anybody anything. If you do, you start missing everybody."`, "The Catcher in the Rye")
    is(`"I'm not afraid of storms, for I'm learning how to sail my ship."`, "Little Women")
    is(`"I was benevolent and good; misery made me a fiend. Make me happy, and I shall again be virtuous."`, "Frankenstein")
    is(`"Most people were heartless about turtles because a turtle's heart will beat for hours after it has been cut up and butchered. But the old man thought, I have such a heart too."`, "The Old Man and the Sea")
    is(`"The sky above the port was the color of television, tuned to a dead channel."`, "Neuromancer")
    is(`"Anything worth dying for is certainly worth living for."`, "Catch-22")
    is(`"I wanted you to see what real courage is, instead of getting the idea that courage is a man with a gun in his hand. It's when you know you're licked before you begin but you begin anyway and you see it through no matter what."`, "To Kill a Mockingbird")
    is(`"Call me Ishmael."`, "Moby Dick")
    is(`"Not all those who wander are lost."`, "The Lord of the Rings")
    is(`"It is to the credit of human nature that, except where its selfishness is brought into play, it loves more readily than it hates."`, "The Scarlet Letter")
    // constellations trivia(incomplete)
    is("What is the brightest star in the Lyra constellation?", "Vega")
    is("Which is the brightest star in the Canis Major constellation?", "Sirius")
    is("This bright star in Auriga is yellow like our sun.", "Capella")
    is("The constellation Libra represents a ___________.", "Balance Scale")
    is("Which constellation holds the brightest star in the north sky?", "Canis Major")
    is("The Auriga constellation is in the shape of a __________.", "Charioteer")
    is("What is the brightest star in Cygnus?", "Deneb")
    is("The constellation Cygnus is in the shape of what bird?", "Swan")
    is("Canis Major is otherwise known as the Great _____.", "Dog")
    is("What is the brightest star in the Pegasus constellation?", "Enif")
    is("Capricornus is in the shape of what mythical animal?", "Sea-Goat")
    is("Cancer is a constellation in the shape of what animal?", "Crab")
    // dinosaur trivia(incomplete)
    is("Who coined the term 'dinosauria?'", "Sir Richard Owen")
    is("In what era did dinosaurs live?", "Mesozoic")
    is("In what period did the Coelophysis live?", "Late Triassic")
    is("Which dinosaur had hollow limb bones?", "Coelophysis")
    is("What does the name 'Triceratops' mean?", "three-horned face")
    is("What profession studies dinosaur fossils?", "Paleontologist")
    is("What does the word 'dinosaur' mean?", "Terrible Lizard")
    is("What caused the extinction of dinosaurs according to scientists?", "Scientists are not 100% sure. There is still heavy debate.")
    is("In what period did the Stegosaurus live?", "Late Jurassic")
    is("Which dinosaur had a long neck to help reach high and low vegetation?", "Diplodocus")
    is("Which of the following was not a flying reptile?", "Stegosaurus")
    is("Which dinosaur most closely resembles a rhinoceros?", "Triceratops")
    // poets trivia (ctrl + shift + p)
    is(`Who Wrote "If You Forget Me"?`, "Pablo Neruda")
    is(`Who wrote "A Dream Within A Dream"?`, "Edgar Allan Poe")
    is(`Who Wrote "I Carry Your Heart With Me"?`, "E.E. Cummings")
    is(`Who wrote "The Road Not Taken"?`, "Robert Frost")
    is(`Who wrote "Life is Fine"?`, "Langston Hughes")
    is(`Who wrote "A Girl"?`, "Ezra Pound")
    is(`Who wrote "Phenomenal Woman"?`, "Maya Angelou")
    is(`Who wrote "Funeral Blues"?`, "W.H. Auden")
    is(`Who wrote "If those I loved were lost"?`, "Emily Dickinson")
    is(`Who wrote "Where the Sidewalk Ends"?`, "Shel Silverstein")
    is(`Who wrote "Messy Room"?`, "Shel Silverstein")
    is(`Who wrote "There is Another Sky"?`, "Emily Dickinson")
    is(`Who wrote "Stopping by the Woods on a Snowy Evening"?`, "Robert Frost")
    is(`Who wrote "To You"?`, "Walt Whitman")
    is(`Who wrote "Do Not Go Gentle To That Good Night"?`, "Dylan Thomas")
    is(`Who Wrote "Let America Be America Again"?`, "Langston Hughes")
    //heart trivia
    is("Which ventricle pumps oxygen-rich blood to the body?", "Left ventricle")
    is("Which artery carries blood from the heart to the lungs?", "Pulmonary Artery")
    is("Which atrium receives oxygen-poor blood from the body?", "Right atrium")
    is("What does the heart do?", "Pumps blood throughout the body")
    is("Which vein carries oxygen-rich blood to the heart from the lungs?", "Pulmonary Veins")
    is("Which of the following is not a systemic artery?", "Pulmonary Artery")
    is("What is a normal resting heart rate for adults over the age 18?", "60-100 bpm")
    is("What blood vessel carries oxygen-rich blood to the body?", "Artery")
    is("Where is the heart located?", "Chest")
    is("What tiny blood vessels transport blood from an artery to a vein?", "Capillaries")
    is("What does the heart pump?", "Blood")
    is("What is the name of the largest artery in the body?", "Aorta")
    // solar system trivia
    is("What man-made objects exist in our solar system?", "Satellites & Space Junk")
    is("Uranus has a __ glow to it.", "Blue")
    is("What is the correct term for Pluto?", "Dwarf Planet")
    is("Which planet is closest to the sun?", "Mercury")
    is("Which planet is furthest from the sun?", "Neptune")
    is("Which is the smallest planet in the solar system?", "Mercury")
    is("Every object in our solar system revolves around the __.", "Sun")
    is("Mars is known as the _ planet.", "Red")
    is("Saturn is famous for its __ that rotate around it.", "Rings")
    is("What are comets made of?", "Dirty Ice")
    is(`Which two planets are Earth's "neighbors"?`, "Venus & Mars")
    is("What is the largest planet in the solar system?", "Jupiter")
    // norse mythology trivia
    is("Who was the goddess of spring?", "Eostre")
    is("Who was the goddess of fertility and plough?", "Gefjun")
    is("Baldr was the god of what?", "Beauty, innocence, peace and rebirth")
    is("Who was the god of mischief?", "Loki")
    is("Who was the goddess of prudence?", "Snotra")
    is("Who was the god of strength and son of Thor?", "Magni")
    is("Who was the goddess of the sea?", "Ran")
    is("Who was the first Norse god?", "Buri")
    is("Who was the wife of Thor and goddess of the harvest?", "Sif")
    is(`Who was the god of war and the "All Father"?`, "Odin")
    is("Who was the god of thunder and battle?", "Thor")
    is("Who was the goddess of healing?", "Eir")
    //landforms trivia
    is("What forms Aeolian landforms?", "Wind")
    is("Bayou, Gully, Marsh and Shoal are examples of what?", "Fluvial landforms")
    is("Which of the following are not associated with fluvial landforms?", "Volcanoes")
    is("Which of the following is not considered a tectonic landform?", "Sinkhole")
    is("Impact landforms are caused by __ impacts.", "Extraterrestrial")
    is("Erosion landforms are caused by what?", "Weathering")
    is("Which of the following is not considered an Aeolian landform?", "Sound")
    is("Which type of rock is not generally a cause for karst typography?", "Granite")
    is("Which of the following is not considered a karst landform?", "Valley")
    is("Which of the following is not considered a slope landform?", "Pull apart basin")
    is("Which of the following is not considered a mountain or glacial landform?", "Oasis")
    is("Caldera, Maar, Vent, and Tuya are examples of what?", "Volcanic landforms")
    // agh im tired of answering trivia

        if(!done) {
         google()
    }
})();
